# Vectors and Matrices in Numpy - Lab

## Introduction

This lab will ask you to perform some simple matrix creation and manipulation exercises based on what we have covered so far in this section. The key takeaway here for you is to be able to understand how to using indexing with matrices and vectors while applying some basic operations.

## Objectives
You will be able to:
* Define vectors and matrices in NumPy
* Check the shape of vectors and matrices
* Access and manipulate individual scalar components of a matrix. 

## 1. Define two arrays A (4x3) and B (3x2) 
```
A = 1402, 191 
    1371, 821 
    949, 1437
    147, 1448
    
B = 1, 2, 3
    4, 5, 6
    ```

In [32]:
import numpy as np
import random

In [22]:
A = np.array([[1402,191],[1371,831],[949,1437],[147,1448]])
# print(A)

B = np.array([[1,2,3],[4,5,6]])
# print(B)
print ('A=\n', A)
print ('B=\n', B)


A=
 [[1402  191]
 [1371  831]
 [ 949 1437]
 [ 147 1448]]
B=
 [[1 2 3]
 [4 5 6]]


## 2. Print the dimensions of A and B 

In [23]:
# Code Here
print('A Shape: ', A.shape)
print('B Shape: ', B.shape)

A Shape:  (4, 2)
B Shape:  (2, 3)


## 3. Print some of the elements from A at following locations
* first row and first column
* first row and second column
* third row and second column
* fourth row and first column

In [29]:
print('First Row, First Column: ', A[0,0])
print('First Row, Second Column: ', A[0,1])
print('Third Row, Second Column: ', A[2,1])
print('Fourth Row, First Column: ', A[3,0])

First Row, First Column:  1402
First Row, Second Column:  191
Third Row, Second Column:  1437
Fourth Row, First Column:  147


In [53]:
# Output should be:

1402
191
1437
147


## 4. Write a routine to populate matrix with random data
* Create an 3x3 numpy array with all zeros (use `np.zeros()`)
* Access each location i,j of this matrix and fill in random values between the range 1 and 10. 

In [30]:
M = np.zeros((3,3))
print ('before random data:\n',M)

before random data:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [41]:
M.shape[4]

IndexError: tuple index out of range

In [34]:
#COPIED THIS FROM THE SOLUTION - WOULD'VE NEVER GOTTEN THIS MYSELF
for x in range(0, M.shape[0]): #changing m.shape[0] to '3' returns the same results M.shape[0] is just the length of the first row of matrix
    for y in range(0, M.shape[1]): #m.shape[1] is just the shape 
        M[x][y] = random.randrange(1, 10) 
print ('\nafter random data:\n',M)


after random data:
 [[5. 8. 9.]
 [6. 7. 3.]
 [3. 5. 3.]]


In [54]:
# Code Here (due to random data , your output might be different)

before random data:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

after random data:
 [[2. 7. 5.]
 [7. 9. 3.]
 [6. 5. 9.]]


## 5. Turn above routine into a function.
* Create two 4x4 zero valued matrices and fill with random data using the function
* Add the matrices together in numpy 
* Show the results

In [44]:
# Now we turn the above into a function that takes in 2 parameters
def fill(matrix):

    for x in range(0, matrix.shape[0]):
        for y in range(0, matrix.shape[1]):
            matrix[x][y] = random.randrange(1, 10)
    
    return matrix

M1 = np.zeros((4,4))
M2 = np.zeros((4,4))

M1_filled = fill(M1)
M2_filled = fill(M2)
out = M1_filled + M2_filled

print ('Final output\n\n', out)

Final output

 [[16.  4.  3. 15.]
 [11. 12.  8.  5.]
 [10. 11. 15.  8.]
 [12. 14. 10.  7.]]


In [55]:
# Code Here (due to random data , your output might be different)

Final output

 [[12.  4. 13.  8.]
 [13.  5.  9.  9.]
 [11. 11. 11. 17.]
 [16. 14.  8. 10.]]


## Summary 

In this lab, we saw how to create and manipulate vectors and matrices in numpy. We shall now move forward to learning more complex operations including dot products and inverses. 